directories:
  output: instalador-final
  buildResources: build
appId: com.joyeriaadri.stock
productName: Chicas de Buenos Aires
files:
  - filter:
      - dist/**/*
      - public/**/*
      - main.js
      - package.json
win:
  target: nsis
  icon: public/logo.png
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  shortcutName: Chicas de Buenos Aires
electronVersion: 41.1.1
